baseurl = "https://logicmonitor.github.io/k8s-argus"
languageCode = "en-us"
title = "Argus"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
publishDir = "../../docs"

[params]
	# General information
	author = "LogicMonitor, Inc."
	description = "Automated Kubernetes monitoring."
	copyright = "Released under Mozilla Public License 2.0"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/logicmonitor/k8s-argus"

	version = "4.2.0"
	logo = "/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-purple"
    	accent  = "deep-purple"

    [params.font]
    	text = "Brandon Grotesque"
    	code = "Roboto Mono"


[social]
	twitter = "LogicMonitor"
	github  = "LogicMonitor"
	email   = "argus@logicmonitor.com"


[[menu.main]]
	name   = "Argus"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 2

[[menu.main]]
	name   = "Docs"
	url    = "docs/"
	weight = 3

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 4


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
